version: 1
disable_existing_logers: False
formatters:
    verbose:
        format: '%(asctime)s -- %(process)d %(levelname)s %(name)s %(thread)d %(message)s'
    simple:
        format: '%(levelname)s %(message)s'
    json:
        (): sanicms.loggers.JsonFormatter
handlers:
    console:
        level: DEBUG
        class: logging.StreamHandler
        formatter: verbose
    json:
        level: DEBUG
        class: logging.StreamHandler
        formatter: json
    file:
        level: INFO
        class: logging.handlers.RotatingFileHandler
        formatter: json
        filename: info.log
        maxBytes: 1024000
        backupCount: 10
loggers:
    root:
        handlers: [console]
        propagate: True
        level: DEBUG
    sanic:
        handlers: [json]
        propagate: True
        level: DEBUG
    zipkin:
        handlers: [json]
        propagate: True
        level: DEBUG
    logstash:
        handlers: [file]
        propagate: True
        level: DEBUG
